Added: #1076 Custom naming pem and key files
sigstore/cosign pull request #1077
Opened 2021-11-18 19:26 UTC by Knibbaz

Closes #1076

You as a user can now give the files a custom name, if you are lazy the files still get the name cosign.pub and cosign.key.

2021-11-18 19:33 UTC, Knibbaz commented
Thought I didn't add the second commit

2021-11-26 18:41 UTC, dlorenc commented
Looks like you missed the DCO still - can you get that signed so we can take a look?

2021-11-29 09:41 UTC, developer-guy requested changes

2021-11-29 09:41 UTC, developer-guy commented on cmd/cosign/cli/generate/generate_key_pair.go
> +	if name == "" {
why don't you just specify this value as the flag's default value, wouldn't it be better?

```go
cmd.Flags().StringVar(&o.Name, "name", "cosign", "adds a choosen name to your .pub and .key files")
```

2021-11-29 09:41 UTC, developer-guy commented on cmd/cosign/cli/generate/generate_key_pair.go
> +	if fileExists(name + ".key") {
maybe we can create a local variable that holds this whole name, then we can use it everywhere we need, WDYT?

2022-03-08 13:49 UTC, dlorenc commented
Closing, please reopen if you get DCO working.

2022-03-08 13:49 UTC, closed without merging

2022-06-21 13:58 UTC, patflynn commented
@Knibbaz Do you think you'll be able  to get DCO working and resubmit?  If not let me know and I'll push it up for you.