Enable CodeQL runs on PRs and weekly
sigstore/cosign pull request #1325
Opened 2022-01-15 12:24 UTC by bobcallaway

Fixes #1324

Signed-off-by: Bob Callaway <bob.callaway@gmail.com>

#### Summary

#### Ticket Link

Fixes

#### Release Note

```release-note

```

2022-01-15 12:55 UTC, dlorenc commented
So we need it on PR runs as well as the cron? It takes an incredibly long time and almost never fails so I've been trying to leave it for post-submit only.

I think we've only ever had one failure here and it was a false positive.

2022-01-17 08:44 UTC, cpanato commented on .github/workflows/codeql-analysis.yml
> +        go-version: '1.16.x'
why 1.16 and not 1.17?

2022-01-17 08:45 UTC, cpanato commented
> So we need it on PR runs as well as the cron? It takes an incredibly long time and almost never fails so I've been trying to leave it for post-submit only.
> 
> I think we've only ever had one failure here and it was a false positive.

i agree, a post-job is good and this does not hurt much us

2022-08-28 15:25 UTC, cpanato requested changes

2022-08-28 15:25 UTC, cpanato commented on .github/workflows/codeql-analysis.yml
> +        go-version: '1.16.x'
@bobcallaway we are using go1.18, can you update to that?

2022-09-14 14:53 UTC, cpanato commented on .github/workflows/codeql-analysis.yml
> +        go-version: '1.16.x'
now maybe 1.19 :)

2022-10-23 07:45 UTC, hectorj2f commented
I've seen PR checks to slow down a lot, we need to measure how much time, it will take. Otherwise I'll suggest to run them post push.

2022-12-04 02:02 UTC, closed without merging