Remove sget command
sigstore/cosign pull request #1364
Opened 2022-01-26 15:06 UTC by luhring

#### Summary

Removes the `sget` command for now, while the team refines the vision for the "sget" idea, how it will be manifested in code, and how we'll distribute it to users.

#### Ticket Link

Related to #1363 

#### Release Note

```release-note
Removes sget command
```

2022-01-26 15:10 UTC, cpanato requested changes
also need to remove from the goreleaser:
https://github.com/sigstore/cosign/blob/main/.goreleaser.yml#L147

and from build image using ko
https://github.com/sigstore/cosign/blob/main/Makefile#L140
https://github.com/sigstore/cosign/blob/main/release/release.mk#L22

and general build
https://github.com/sigstore/cosign/blob/main/Makefile#L92

2022-01-26 15:36 UTC, luhring commented
Thanks @cpanato for finding those! 🙏 

I also found a handful of other spots we're using the `sget` command, and I removed them. Let me know if this was too heavy-handed.

Also, I left the `sget` Go package for now, since it's used in `cosign policy init` and in E2E testing. Let me know if you think we should work to remove this "sget" reference as well.

2022-01-26 16:40 UTC, cpanato submitted a review, later dismissed
LGTM

will defer to @dlorenc

2022-01-26 16:41 UTC, cpanato commented
would merge this after the 1.5.1 release

2022-01-26 18:19 UTC, luhring commented
> I'd honestly still rather wait here until we have a plan. I don't think it's going to take forever to get something drafted, but doing it in a rush before we've figured out what the next step is feels like a mistake.

Agreed 💯 . Let's do that, and this PR is here if/when we want it.

2022-02-02 23:40 UTC, dlorenc commented
Ok so for a plan, we can leave this around until the new repo is created and we've done a release from there. That way we can delete here without causing too much confusion.

2022-04-16 17:33 UTC, jeff-mccoy commented
Thanks @dlorenc...we already included the `sget` package in our go project not realizing it was possibly being removed 😳.  Thanks to @imjasonh for pointing this out to us in slack.

2022-09-06 12:51 UTC, imjasonh commented
@dlorenc ping, possibly https://github.com/sigstore/cosign/pull/2019 first?

2022-10-10 13:42 UTC, imjasonh commented
I think we can do this now.

#2019 was merged in https://github.com/sigstore/cosign/commit/1f42a247b80d34f1deecfdf61ce8b5e3a858308b and released as part of cosign 1.12. We're on 1.13 now, so I think this is ample warning for folks to stop depending on it.

WDYT @dlorenc

2022-10-13 17:39 UTC, cpanato commented
@imjasonh, when we make the release of the sget in the other repo we will continue the release version of sget and do a  `v1.14.0` lets, say.

2022-11-13 07:44 UTC, cpanato commented
Not stale

2023-02-14 08:21 UTC, cpanato commented
@luhring @imjasonh @dlorenc any plans on this? should we move forward or close this PR?

2023-02-14 17:04 UTC, znewman01 commented
I think we should merge this PR. As-is, sget is only marginally useful. There's no real replacement but then again sget itself was never complete and often encouraged security antipatterns.

2023-03-28 01:12 UTC, luhring commented
> I think we should merge this PR.

Just catching up here! 😅  I'm happy to go through the merge conflicts and resolve them if current maintainers are still into this change! Otherwise we can close this.

2023-03-28 16:52 UTC, priyawadhwa commented
Removing it sgtm!

2023-04-06 11:08 UTC, cpanato commented on .goreleaser.yml
> +  main: ./cmd/cosign/webhook
from where this come from? this was deprecated a long time and not have it own repo (policy-controller)

2023-04-06 11:09 UTC, cpanato commented
@luhring maybe you rebased using an older base?
it is okay to close this and I open a fresh one?

2023-04-06 11:32 UTC, luhring commented
@cpanato Please! 🙏

2023-04-09 10:20 UTC, cpanato commented
closing in favor of https://github.com/sigstore/cosign/pull/2885

2023-04-09 10:20 UTC, closed without merging