fix: rekor get tlog entry with uuid
sigstore/cosign pull request #2058
Opened 2022-07-08 18:05 UTC by asraa

Signed-off-by: Asra Ali <asraa@google.com>

Sign blob otherwise doesn't work, because the UUID in the response of Rekor now includes a prefix shard UUID.

cc @priyawadhwa 

#### Summary

#### Release Note

#### Documentation

2022-07-11 10:10 UTC, priyawadhwa approved these changes
nice!!

2022-07-11 14:38 UTC, dlorenc commented
Codegen or a rebase issue?

2022-07-11 15:35 UTC, priyawadhwa commented
I think an issue with compiling cosign, we might need to update to 1.18:

```
Error: ../../../go/pkg/mod/sigs.k8s.io/release-utils@v0.7.1/version/version.go:124:25: bi.Settings undefined (type *debug.BuildInfo has no field or method Settings)
note: module requires Go 1.18
```

2022-07-11 15:39 UTC, asraa commented
> I think an issue with compiling cosign, we might need to update to 1.18:

yeah, i'm seeing some problems when i run codegen locally as well. is this because rekor is at 1.18?

2022-07-11 15:44 UTC, priyawadhwa commented
I think that `sigs.k8s.io/release-util` dependency requires 1.18. looks like rekor recently pinned to a specific version of it and updated the go version at the same time -- https://github.com/sigstore/rekor/pull/904

2022-08-03 14:43 UTC, asraa commented
Confirmed this fixes goreleaser:
```
$ COSIGN_EXPERIMENTAL=1 ./cosign verify-blob   --signature https://github.com/goreleaser/goreleaser/releases/download/v1.10.3/checksums.txt.sig   https://github.com/goreleaser/goreleaser/releases/download/v1.10.3/checksums.txt
tlog entry verified with uuid: 6ad8e71d61e4757a7010ba3d31fca287db1e1e3ecdc09ebaeab317b7974f2581 index: 3045145
Verified OK
```

2022-08-03 14:44 UTC, asraa commented
@priyawadhwa @dlorenc @hectorj2f sorry this got lost after the golang bump! but this will fix the recent goreleaser issue so I am reviving it.

2022-08-03 15:05 UTC, asraa commented
Once again I have some dep problems... :/

2022-08-03 15:55 UTC, caarlos0 submitted a review, later dismissed

2022-08-03 16:31 UTC, asraa commented
@imjasonh I think I still require go 1.18 https://github.com/sigstore/cosign/pull/2093

2022-08-14 19:42 UTC, dlorenc commented
You should be able to rebase now!

2022-08-15 14:33 UTC, asraa commented
Updated, thank you!

Note the comment in the dep check: If needed, I'll see if I can split up the sharding package's sharding computation from the stuff that requires Trillian clients.

2022-08-15 14:36 UTC, imjasonh submitted a review, later dismissed

2022-08-15 15:53 UTC, dlorenc approved these changes

2022-08-15 15:54 UTC, dlorenc requested changes
Actually we need to hold on the trillian dep check I think, cc @vaikas and @mattmoor

2022-08-15 16:02 UTC, asraa commented
> Actually we need to hold on the trillian dep check I think, cc @vaikas and @mattmoor

Yeah, if this can't be WIP for a little time, I can copy/paste the sharding code with a TODO to remove the copy-paste. LMK

2022-08-16 14:22 UTC, vaikas commented
I'd personally prefer to not pull that in as it has caused (well, not Trillian alone, but things with glog and other huge deps. My preference would be (I can't believe I'm saying this ;) ) cut&paste.

When you say it would be wip for little time, what's the actual fix that we would have to do?

But from this PR I don't quite get why we need to comment out the trillian bit, this doesn't seem to bring in new deps added, so I don't understand why we need to remove it.
My second question is just curiousity about leaking the the implementation details (but we don't have to discuss it here) about the trillian that sits behind rekor.

2022-08-16 14:32 UTC, vaikas commented
Also, I know folks are sensitive to deps and sizes (I know when I inadvertently pulled in something that had a k8s dep :) )

2022-08-16 14:40 UTC, asraa commented
> Or, as @vaikas says, copy and paste sharding.GetUUIDFromIDString into cosign.

Yeah exactly. I could either do this, since it's not complicated logic, but my main idea was to separate these sharding utils from the sharding code that manipulates and requires the trillian log client.

I'll resolve it internally. Before GA we will expose verification libraries with few deps in rekor anyway. And that will supersede all this code.

2022-08-16 16:15 UTC, asraa commented
All set, PTAL. Added tests for all the cases of whether Rekor will return EntryUUIDs or UUIDs to make sure matching occurs correctly.

2022-08-16 16:53 UTC, dlorenc approved these changes

2022-08-16 17:00 UTC, merged