note: Adds documentation migration note to IMPORT.md
sigstore/cosign pull request #2585
Opened 2023-01-02 20:12 UTC by ChrisJBurns

Adds documentation migration note to `IMPORT.md` as it has been migrated as part of `sigstore/docs` [PR#54](https://github.com/sigstore/docs/pull/54) and issue https://github.com/sigstore/cosign/issues/822 

Signed-off-by: ChrisJBurns <29541485+ChrisJBurns@users.noreply.github.com>

2023-01-02 20:14 UTC, ChrisJBurns commented
@znewman01 

The deprecation note to the `IMPORT.md` docs that was added to `sigstore/docs` in  https://github.com/sigstore/docs/pull/54, as [discussed here](https://github.com/sigstore/cosign/issues/822#issuecomment-1368936223).

2023-01-02 20:59 UTC, znewman01 submitted a review, later dismissed
I think you could actually kill the text here since your link is live. Up to you, approving either way

2023-01-02 21:08 UTC, ChrisJBurns commented
@znewman01  Shall kill in that case. Will push up the change now

2023-01-02 21:30 UTC, znewman01 requested changes
I should have been clearer.

I meant to kill the *text* of the file but leave the "note" you had that redirected users to the migrated content. I think we probably have a few old links to this page lying around.

Sorry for the runaround!

2023-01-02 21:31 UTC, ChrisJBurns commented
@znewman01 

Ahhh, I see, no problemo, shall push up amendment in a jiffy

2023-01-03 14:56 UTC, znewman01 approved these changes
Perfect, thanks for your patience!

2023-01-03 14:56 UTC, merged