feat: add riscv64 arch
sigstore/cosign pull request #2821
Opened 2023-03-19 13:01 UTC by ernado

Add riscv64 to `.goreleaser.yml` `goarch`, also update `test/e2e_test_secrets.sh` (not sure about that).

Also, it looks like no `riscv64` image is available:
```console
$ docker pull gcr.io/projectsigstore/cosign:v2.0.0
v2.0.0: Pulling from projectsigstore/cosign
no matching manifest for linux/riscv64 in the manifest list entries
```
But it should, because latest `ko` version should build for `linux/riscv64` with flag `--platform=all`, how can I fix that?

2023-03-19 13:34 UTC, developer-guy commented
> But it should, because latest ko version should build for linux/riscv64 with flag --platform=all, how can I fix that?

Hello @ernado, thanks for the PR, you don't need to do anything special since ko relies upon the GOOS and GOARCH parameters to decide on the os/arch.

2023-03-19 13:34 UTC, developer-guy approved these changes
LGTM

2023-03-20 08:36 UTC, cpanato requested changes
Thanks for your PR, just make it clear, this will build the binary for `riscv64` not the container image (as you post in the PR summary) 
the base image we use to build cosign does not have `riscv64` in their manifest so we cannot build that one

```
$ crane manifest gcr.io/distroless/base:debug-nonroot
{
  "schemaVersion": 2,
  "mediaType": "application/vnd.oci.image.index.v1+json",
  "manifests": [
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 2275,
      "digest": "sha256:1f42a01908b9f0f8c2bddf03357282c9a681143f9110579d9e93be522d77c6d3",
      "platform": {
        "os": "linux",
        "architecture": "amd64"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 2275,
      "digest": "sha256:071216296b505906a7ed9a6098bd7fe8c0023193ff79c41145d86b9790fee514",
      "platform": {
        "os": "linux",
        "architecture": "arm64"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 2275,
      "digest": "sha256:71b7cc693a627307e946f108fc7d664cabc526bb90a96267921648de37c95b46",
      "platform": {
        "os": "linux",
        "architecture": "arm"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 2275,
      "digest": "sha256:abec858b227883a2f8deaf04015b8dab52bd10a4580118fcaf15a5dad84c4d05",
      "platform": {
        "os": "linux",
        "architecture": "s390x"
      }
    },
    {
      "mediaType": "application/vnd.oci.image.manifest.v1+json",
      "size": 2275,
      "digest": "sha256:6f19439dfe795361456c82bc6c94388809abfde9a1b181c80c3e06dfe084dc55",
      "platform": {
        "os": "linux",
        "architecture": "ppc64le"
      }
    }
  ]
}
``` 

the change for the binary LGTM, please drop the other change

2023-03-20 08:36 UTC, cpanato commented on test/e2e_test_secrets.sh
> +for arch in "linux/amd64" "linux/arm64" "linux/s390x" "linux/riscv64"
you can drop this

2023-03-20 08:45 UTC, ernado commented on test/e2e_test_secrets.sh
> +for arch in "linux/amd64" "linux/arm64" "linux/s390x" "linux/riscv64"
done

2023-03-20 08:48 UTC, ernado commented
Thank you for clarifying! 

For the record: distroless image for `riscv64` will be available only when Debian will be released with stable `riscv64` port, my assumption is Debian 13 in 2025 (ref: https://github.com/GoogleContainerTools/distroless/issues/1269).

2023-03-24 13:40 UTC, ernado commented
Gentle ping @cpanato 
Is there anything that I should fix here?

2023-03-24 13:41 UTC, cpanato approved these changes
thanks

2023-03-24 13:42 UTC, merged