RFC: Add `sign --docker-reference` CLI
sigstore/cosign pull request #2984
Opened 2023-05-16 10:02 UTC by saschagrunert

#### Summary
The `--docker-reference` flag allows setting the `critical.identity.docker-reference` field in the signature to a different container image reference. This is particularly useful when using proxy mirrors like `registry.k8s.io`, where end-users have no chance to actually assume the underlying registry. This change allows signing images using the mirror/proxy identifier, while validation can then happen without requiring any additional remapping.

#### Release Note

Added `sign --docker-reference` CLI flag.

#### Documentation
TBD.

2023-05-17 13:28 UTC, mtrmac reviewed
I strongly support this feature; it is necessary not only for proxies, but also for many staging workflows (creating an image signed with the production key, with a production identity, but not _publishing_ it yet and storing it in an internal registry).

2023-05-19 06:54 UTC, saschagrunert commented on cmd/cosign/cli/options/sign.go
> +	cmd.Flags().StringVar(&o.DockerReference, "docker-reference", "",
I'm also happy with `--sign-identity`, what do the other maintainers think?

2023-05-19 09:07 UTC, cpanato submitted a review, later dismissed
lgtm

we just need to remove the replace when the PR from sigstore/sigstore is merged

2023-05-22 15:38 UTC, haydentherapper commented on cmd/cosign/cli/options/sign.go
> +	cmd.Flags().StringVar(&o.DockerReference, "docker-reference", "",
It’s a little confusing to reuse identity, since we use identity already to refer to who is doing the signing. Maybe sign-container-identity?

2023-05-31 14:39 UTC, znewman01 requested changes
This looks great, thanks for the change.

I see there's a little bit of worry about the flag name. I'm empathetic: it's a little weird to say the *image* has an identity, especially when there's also a signer identity in play. 

I don't want to bikeshed too much further, but maybe the name is a *little* less important if we can make the help text a bit more explicit and to add an example to the [`cosign sign` docs](https://github.com/sigstore/cosign/blob/0a4db33042b527640ffe29dfa558bd21fbcba987/cmd/cosign/cli/sign.go#L42).

My *way too wordy* version, written to check my own understanding here, would be:

> `cosign sign` uses the ["simple signing"](https://github.com/containers/image/blob/a5061e5a5f00333ea3a92e7103effd11c6e2f51d/docs/containers-signature.5.md#json-data-format) format for signatures, which links an image with a given digest to a `docker-reference`: basically, "image `sha256@...` is `alpine:latest`." By default, we infer the docker reference based on what you sign; this flag allows you to override that (for instance, to specify a tag instead of a digest, or when using a proxy).


Maybe something like:

> `--sign-identity`: claim that the image being signed has the given identity (instead of inferring this from the provided image identifier): sign `my-registry.io/foo@sha256:...` as `my-registry.io/foo:v1` or even `other-registry.io/bar:latest`.

And then add an example like:

```
# sign a container image, identifying it by tag
cosign sign --sign-identity registry.io/foo:latest my-proxy.io/foo@sha256:abcdef 

# sign a container image fetched via a proxy, identifying it by the upstream Docker reference.
cosign sign --sign-identity upstream-registry.io/foo:latest my-proxy.io/foo@sha256:abcdef 
```

Feel free to revise any of the above. But I think if the docs are really clear we can live with an imperfect name.

(This suggests that maybe we eventually want some sugar we'd want for using a tag as the `--sign-identity`: maybe `--sign-identity :tag`. But we can deal with that later).

2023-05-31 14:57 UTC, mtrmac commented
All of the above makes sense to me.

For a bit more context to consider, _separately from his PR_, I’d _afterwards_ like to replace/discourage the currently-recommended `cosign sign repo@sha256:digest` command, because the signature does not include a tag, and matching the tag is an important part of protecting the user against registries/proxies etc. substituting images (giving the user a correctly signed, but old known-vulnerable application version when the user asks for a recent version).

I’m a bit struggling with a good UI… one alternative is to make the `--sign-identity` option strongly recommended in all flows:
```console
$ cosign sign --sign-identity registry.io/foo:latest my-proxy.io/foo@sha256:abcdef 
```

My preference would be, instead, to add yet another option:
```console
$ cosign sign --digest sha256:abcdef registry.io/foo:latest
```
because that can be built “naturally”: a naive user says `cosign sign …foo:latest`, gets a warning/error “please pin what you want to sign, using `cosign sign --digest … foo:latest`”, and the user just adds one more option; vs. recommending the user to use `--sign-identity`, which would require reformulating more of the command line.

That would be an alternative for adding the `--sign-identity :tag` sugar; `--sign-identity` would almost exclusively be used when the registry/repo part differs, making the short-form unnecessary.

2023-05-31 15:10 UTC, znewman01 commented
All SGTM. I think this PR represents a great first step in that direction.

2023-05-31 15:46 UTC, hectorj2f commented on cmd/cosign/cli/options/sign.go
> +	cmd.Flags().StringVar(&o.DockerReference, "docker-reference", "",
I agree with @haydentherapper here.

2023-06-02 08:16 UTC, saschagrunert commented on cmd/cosign/cli/options/sign.go
> +	cmd.Flags().StringVar(&o.DockerReference, "docker-reference", "",
Switched to `--sign-container-identity` naming.

2023-06-02 08:16 UTC, saschagrunert commented
Switched to `--sign-container-identity` for naming, we may want to wait for a sigstore/sigstore release as well.

2023-06-02 13:30 UTC, znewman01 requested changes
I think I'm happy modulo the request for additional examples in the docs (and maybe a slightly longer flag description)!

2023-06-05 17:08 UTC, merged