Add SLSA 1.0 attestation support to cosign. Closes #2860
sigstore/cosign pull request #3219
Opened 2023-09-05 15:44 UTC by ziel

#### Summary
This change adds support for the SLSA 1.0 provenance predicate (https://slsa.dev/spec/v1.0/provenance).

`cosign attest` and related commands cannot validate it currently, and the `custom` type must be used for it instead. After this change, it will be possible to specify the new provenance attestation type as `slsaprovenance1`.

Related issue: https://github.com/sigstore/cosign/issues/2860

#### Release Note
Added a new type `slsaprovenance1` to support slsa 1.0 provenance in attest and verify commands.

#### Documentation
The attestation types do not appear to be documented at https://docs.sigstore.dev so there is no related change there.

2023-09-05 16:10 UTC, haydentherapper commented
I think this is a good way to approach this, and we can plan to change the behavior of the flags in a later release as a breaking change, where `slsaprovenance` will generate a v1.0 attestation and we'll drop support for v0.2.

cc @znewman01

2023-09-05 21:35 UTC, znewman01 requested changes
Maybe to ease the transition can we add a `slsaprovenance0.2` option that's just an alias for the current behavior?

Then we could at some future point switch over `slsaprovenance` to point to `slsaprovenance1`.

Otherwise looks great, thanks for the change!

2023-09-05 21:35 UTC, znewman01 commented on pkg/cosign/attestation/attestation.go
> +// predicate type (custom|slsaprovenance|slsaprovenance1.0|spdx|spdxjson|cyclonedx|link).
nit: `slsaprovenance1`.

2023-09-06 15:06 UTC, ziel commented on pkg/cosign/attestation/attestation.go
> +// predicate type (custom|slsaprovenance|slsaprovenance1.0|spdx|spdxjson|cyclonedx|link).
oh oops! will fix

2023-09-06 21:23 UTC, haydentherapper approved these changes

2023-09-13 18:28 UTC, ziel commented
hi @znewman01 -- i added a patch related to your change request, if you have a moment to peek at it. i called the type `slasprovenance02` because there's places in the code base which don't like the `.` -- though we could have it diverge from the those if that'd be better

2023-09-13 20:07 UTC, znewman01 approved these changes

2023-09-13 20:08 UTC, merged