feat: add platform flag to cosign copy command
sigstore/cosign pull request #3234
Opened 2023-09-10 07:42 UTC by vishal-chdhry

Signed-off-by: Vishal Choudhary <sendtovishalchoudhary@gmail.com>

#### Summary

Fixes: #2748

This PR adds a `--platform` flag to `cosign copy`. This allows copying images and signatures for specific platform/architecture.

/cc @imjasonh @znewman01 @cpanato

#### Release Note
Added `--platform` flag to `cosign copy` command

2023-09-10 16:22 UTC, znewman01 requested changes
Thank you very much for this change! I left some minor feedback

2023-09-10 16:22 UTC, znewman01 commented on cmd/cosign/cli/common/platform.go
> +package common
I think I'd prefer to see this in something like `pkg/oci`

2023-09-10 16:22 UTC, znewman01 commented on cmd/cosign/cli/copy/copy_test.go
> -	}, srcImg, destImg, false, true)
I'd like to see a test that exercises the new behavior.

2023-09-10 16:22 UTC, znewman01 commented on cmd/cosign/cli/copy/copy.go
> +
I know a lot of this is copy-paste from `sbom download`. Is it possible to factor out?

2023-09-10 16:22 UTC, znewman01 commented on cmd/cosign/cli/copy/copy.go
> +			return fmt.Errorf("unable to find an SBOM for %s", targetPlatform.String())
bad message after copy/paste 🙂

2023-09-10 16:22 UTC, znewman01 commented on cmd/cosign/cli/copy/copy.go
> +	if platform != "" && !isIndex {
IMO this is clearer as:

```
func RootForPlatform(root, platform string) string, error {
    if platform == "" {
        // Copy all platforms
        return root, nil
    }
    if !isIndex {
        return fmt.Errorf("...")
    }
   // ...
}

2023-09-10 16:22 UTC, znewman01 commented on cmd/cosign/cli/copy/copy.go
> +	if platform != "" && !isIndex {
That code won't compile as-is, there's a couple other things to thread through but I hope it gets the idea across.

2023-09-16 13:41 UTC, vishal-chdhry commented
@znewman01 I have added a unit test as well as a example in pull request description. Can you please review it again

2023-09-16 14:21 UTC, znewman01 approved these changes

2023-09-16 14:21 UTC, znewman01 commented on doc/cosign_copy.md
> +	# copy a container image and its signatures for a specific platform
nitpick: can you dedent this line?

2023-09-16 14:21 UTC, merged