feat: add support outputting rekor response on signing
sigstore/cosign pull request #3248
Opened 2023-09-17 19:35 UTC by vishal-chdhry

#### Summary

Closes: #3110

Previously, there's no support for outputting a bundle with `cosign sign` ([code](https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/sign/sign.go#L266-L298)), only `sign-blob` ([code](https://github.com/sigstore/cosign/blob/main/cmd/cosign/cli/sign/sign_blob.go#L135-L152)). This PR adds support for outputting rekor response on signing. This supports use-cases where a signer does not want to attach metadata immediately to the container.

#### Release Note

Added support outputting rekor response on signing with `cosign sign`
#### Documentation

2023-09-18 17:06 UTC, haydentherapper requested changes
Can you add a test for this too?

2023-09-18 17:06 UTC, haydentherapper commented on cmd/cosign/cli/sign/sign.go
> +func fetchSignedPayload(sig oci.Signature) (*cosign.SignedPayload, error) {
Can this return a `LocalSignedPayload` instead to be in sync with sign-blob? It should be loadable with https://github.com/sigstore/cosign/blob/main/pkg/cosign/fetch.go#L199.

2023-09-19 20:19 UTC, vishal-chdhry commented
@haydentherapper I have added a test and updated the logic, can you please review it

Besides, I cannot run/debug tests in `test/e2e_test.go`. I think `gopls` is not working for me in that file, autocomplete does not work either. Is there anything I need to configure? I am using VSCode.

2023-10-17 17:35 UTC, haydentherapper submitted a review, later dismissed
One tiny comment, looks good!

2023-10-17 17:35 UTC, haydentherapper commented on test/e2e_test.go
> +	defer setenv(t, env.VariableExperimental.String(), "1")()
Can you remove, the experimental flag is no longer used?

2023-10-17 18:53 UTC, vishal-chdhry commented
@haydentherapper Removed the flag

2023-10-17 19:13 UTC, haydentherapper approved these changes

2023-10-17 19:23 UTC, merged