Update README.md
sigstore/cosign pull request #3268
Opened 2023-09-29 01:04 UTC by jonvnadelberg

add additional doc statement to bottom of file.

update for #3267
#### Summary

#### Release Note

NONE
#### Documentation

Doc only.

2023-10-16 05:49 UTC, haydentherapper requested changes
Can you put this under CONTRIBUTING.md rather than the readme?

2023-10-24 22:50 UTC, jonvnadelberg commented
Moved new text to contributing.md

2023-10-24 22:51 UTC, jonvnadelberg commented
> Can you put this under CONTRIBUTING.md rather than the readme?

Moved to contributing.md as requested.

2023-10-24 22:53 UTC, haydentherapper approved these changes

2023-10-24 23:30 UTC, merged